-- Create users_assets table (formerly "users")
CREATE TABLE IF NOT EXISTS "users_assets" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "users_assets_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"user_id" text NOT NULL,
	"character_name" text NOT NULL,
	"asset_type" text,
	"r2Key" text,
	"asset_url" text NOT NULL,
	"size_bytes" bigint,
	"duration_seconds" numeric,
	"label" text,
	"source_upload_session_id" text,
	"created_at" timestamp DEFAULT now(),
	"updated_at" timestamp DEFAULT now()
);-->statement-breakpoint
-- Create upload_sessions table
CREATE TABLE IF NOT EXISTS "upload_sessions" (
	"id" text PRIMARY KEY,
	"user_id" text NOT NULL,
	"job_id" text,
	"asset_type" text NOT NULL,
	"character_slot" text,
	"status" text NOT NULL,
	"r2_key" text NOT NULL,
	"bucket" text NOT NULL,
	"presigned_url_expires_at" timestamp NOT NULL,
	"expected_content_type" text NOT NULL,
	"expected_size_bytes" bigint,
	"original_filename" text NOT NULL,
	"error" text,
	"confirmed_at" timestamp,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "upload_sessions_r2_key_unique" UNIQUE("r2_key")
);-->statement-breakpoint
-- Add asset_references to jobs if not exists
ALTER TABLE "jobs" ADD COLUMN IF NOT EXISTS "asset_references" jsonb;-->statement-breakpoint
-- Create indexes on upload_sessions
CREATE INDEX IF NOT EXISTS "upload_session_user_id_idx" ON "upload_sessions" USING btree ("user_id");-->statement-breakpoint
CREATE INDEX IF NOT EXISTS "upload_session_job_id_idx" ON "upload_sessions" USING btree ("job_id");-->statement-breakpoint
-- Add FK from users_assets to upload_sessions
DO $$ BEGIN
  ALTER TABLE "users_assets" ADD CONSTRAINT "users_assets_source_upload_session_id_upload_sessions_id_fk" FOREIGN KEY ("source_upload_session_id") REFERENCES "public"."upload_sessions"("id") ON DELETE set null ON UPDATE no action;
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;
